dmillman_kdbt_test:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: fivetran

      # User/password auth
      user: FIVETRAN_DAVID_MILLMAN
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD')}}"

      role: FIVETRAN_INTERNAL
      database: DAVID_MILLMAN
      warehouse: FIVETRAN_INTERNAL
      schema: DBT_SCHEMA
      threads: 4
      client_session_keep_alive: False
      query_tag: DMILLMAN_DBT_QUERIES
